# Generated by Django 4.1.4 on 2022-12-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotasks',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='complete'),
        ),
        migrations.AlterField(
            model_name='todotasks',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
