# Generated by Django 4.1.4 on 2022-12-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todotasks_is_complete_alter_todotasks_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotasks',
            name='description',
            field=models.CharField(default='Description', max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='todotasks',
            name='title',
            field=models.CharField(default='Title', max_length=50, verbose_name='title'),
        ),
    ]
