# Generated by Django 4.1.4 on 2022-12-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todotasks_description_alter_todotasks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotasks',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='todotasks',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todotasks',
            name='title',
            field=models.CharField(default='Title', max_length=50),
        ),
    ]
