# Generated by Django 4.1.4 on 2022-12-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todotasks_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDOTasks',
            new_name='Tasks',
        ),
    ]
