# Generated by Django 4.1.4 on 2022-12-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_todotasks_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
    ]
